USE lqc353_4;

-- Disable foreign key checks
SET FOREIGN_KEY_CHECKS = 0;

SELECT COUNT(*) AS "TOTAL LOCATIONS:" FROM Locations;

SELECT COUNT(*) AS "TOTAL PERSONNEL:" FROM Personnel;

SELECT COUNT(*) AS "TOTAL OPERATING LOCATIONS:" FROM OperatesAt;

SELECT COUNT(*) AS "TOTAL FAMILY MEMBERS:" FROM FamilyMembers;

SELECT COUNT(*) AS "TOTAL CLUB MEMBERS:" FROM ClubMembers;

SELECT COUNT(*) AS "TOTAL PAYMENTS" FROM Payments;


